<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statechart" nsURI="http://a.b.c/x/y/Z" nsPrefix="schart">
  <eClassifiers xsi:type="ecore:EClass" name="Statechart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topState" lowerBound="1"
        eType="#//AND" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//State"
        eOpposite="#//State/rnext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rnext" upperBound="-1"
        eType="#//State" eOpposite="#//State/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rcontains" eType="#//Compound"
        eOpposite="#//Compound/contains"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HyperEdge" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="Basic" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="Compound" abstract="true" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//State" containment="true" eOpposite="#//State/rcontains"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AND" eSuperTypes="#//Compound"/>
  <eClassifiers xsi:type="ecore:EClass" name="OR" eSuperTypes="#//Compound"/>
</ecore:EPackage>
